In [1]:
import numpy as np
from numpy import linalg as LA
import pandas as pd

In [2]:
n = (3, 4) # size of matrix
A = np.random.randn(n[0], n[1])
A

array([[-0.34955916,  0.20794109,  0.92923599, -0.64559013],
       [-0.36723336, -0.3553801 , -0.87210504,  0.36838108],
       [ 0.82042635, -0.1165894 , -0.59047231, -0.26888924]])

In [3]:
q = []
qbar = []
qbar.append(A[:,0])
if(LA.norm(qbar[-1]) == 0):
    q.append(qbar[-1])
else:
    q.append(qbar[-1] / LA.norm(qbar[-1]))

In [4]:
for i in range(1,n[1]):
    x = A[:, i]
    for j in range(0, i):
        x -= np.dot(q[j], np.transpose(A[:, i])) * q[j]
    qbar.append(x)
    if(LA.norm(qbar[-1]) < (10 ^ (-20))):
        q.append(qbar[-1])
    else:
        q.append(qbar[-1] / LA.norm(qbar[-1]))

In [5]:
Q = np.transpose(np.array(q))


In [6]:
Q

array([[-0.36244647,  0.45460763,  0.81361198, -0.54815097],
       [-0.38077228, -0.86901898,  0.31594063,  0.4796321 ],
       [ 0.85067328, -0.19528932,  0.48807485,  0.68518871]])

In [7]:
np.dot(np.transpose(Q), Q)

array([[ 1.00000000e+00, -2.84735830e-17,  8.74422406e-16,
         5.98916505e-01],
       [-2.84735830e-17,  1.00000000e+00, -1.23274564e-15,
        -7.99813043e-01],
       [ 8.74422406e-16, -1.23274564e-15,  1.00000000e+00,
         3.99764476e-02],
       [ 5.98916505e-01, -7.99813043e-01,  3.99764476e-02,
         1.00000000e+00]])

In [8]:
R = []
for i in range(0, n[1]):
    T = []
    for j in range(0, n[1]):
        if(i == j):
            T.append(LA.norm(qbar[i]))
        elif(i > j):
            T.append(0)
        else:
            T.append(np.dot(q[i], np.transpose(A[:, j])))
    R.append(T)
R = np.array(R)

In [9]:
R

array([[ 9.64443539e-01, -1.38777878e-17,  1.66533454e-16,
         4.85217345e-16],
       [ 0.00000000e+00,  4.26132324e-01, -2.46330734e-16,
        -6.47975400e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.92309437e-01,
         3.23872620e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.10158580e-16]])

In [10]:
np.dot(Q, R)

array([[-3.49559161e-01,  1.93723004e-01,  1.56465263e-01,
        -8.88178420e-16],
       [-3.67233364e-01, -3.70317078e-01,  6.07583654e-02,
         7.77156117e-16],
       [ 8.20426346e-01, -8.32190919e-02,  9.38613993e-02,
         1.11022302e-15]])

In [11]:
A

array([[-3.49559161e-01,  1.93723004e-01,  1.56465263e-01,
        -4.44089210e-16],
       [-3.67233364e-01, -3.70317078e-01,  6.07583654e-02,
         3.88578059e-16],
       [ 8.20426346e-01, -8.32190919e-02,  9.38613993e-02,
         5.55111512e-16]])